name: Sync Upstream Repo

# 每天一次定时触发，也可以根据需求调整，如："0 3 * * *"表示每天凌晨3点执行
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v3

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: |
          # 将此处的地址替换为你想同步的仓库地址
          git remote add upstream https://github.com/vernesong/OpenClash.git
      
      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream changes using subtree
        run: |
          # 如果你希望同步其他分支，例如 dev 分支中的 package/special 文件夹
          # 将 "upstream/main" 修改为 "upstream/dev"，并将 --prefix 参数修改为你需要的目录路径
          git subtree pull --prefix=luci-app-openclash upstream dev --squash || echo "No updates"

      - name: Push changes if any
        run: |
          if [[ `git status --porcelain` ]]; then
            git push origin main
          else
            echo "No changes to push"
          fi
